/**
  * YtelAPILib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('YtelAPILib')
    .factory('AudioDirectionEnum', [AudioDirectionEnumModel]);

    function AudioDirectionEnumModel() {
        return {
            //TODO: Write general description for this element
            MIN: 'in',
    
            //TODO: Write general description for this element
            OUT: 'out'
        };
    }

}(angular));
