/**
  * YtelAPILib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('YtelAPILib')
    .factory('AudioUrlEnum', [AudioUrlEnumModel]);

    function AudioUrlEnumModel() {
        return {
            //mp3 file
            MP_3: 'mp3',
    
            //wav file
            WAV: 'wav'
        };
    }

}(angular));
