/**
  * YtelAPILib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('YtelAPILib')
    .factory('MActivateEnum', [MActivateEnumModel]);

    function MActivateEnumModel() {
        return {
            //TODO: Write general description for this element
            ACTIVATE: 1,
    
            //TODO: Write general description for this element
            DE_ACTIVATE: 0
        };
    }

}(angular));
