/**
  * YtelAPILib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('YtelAPILib')
    .factory('MergeNumberStatusEnum', [MergeNumberStatusEnumModel]);

    function MergeNumberStatusEnumModel() {
        return {
            //TODO: Write general description for this element
            MDELETE: 0,
    
            //TODO: Write general description for this element
            MERGE: 1
        };
    }

}(angular));
