/**
  * YtelAPILib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('YtelAPILib')
    .factory('PlayDtmfDirectionEnum', [PlayDtmfDirectionEnumModel]);

    function PlayDtmfDirectionEnumModel() {
        return {
            //in direction
            MIN: 'in',
    
            //out direction
            OUT: 'out',
    
            //both
            BOTH: 'both'
        };
    }

}(angular));
