/**
  * YtelAPILib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('YtelAPILib')
    .factory('Status24Enum', [Status24EnumModel]);

    function Status24EnumModel() {
        return {
            //Interrupt Call will be cancel
            CANCELED: 'canceled',
    
            //Interrupt Call is complete
            COMPLETED: 'completed'
        };
    }

}(angular));
