/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';
angular.module('YtelAPIV3Lib')
    .factory('ModelFactory', ['Errors', 'TemplateData', 'MError', 'Message',ModelFactory]);

	/**
	 * Factory service to create instances of models and exception classes
	 */
    function ModelFactory(Errors, TemplateData, MError, Message) {

		var classMap = {
            Errors: Errors,
            TemplateData: TemplateData,
            MError: MError,
            Message: Message
		};

		return {
		    /**
		     * Creates instance of a model class
		     * @param  modelName  {string}  Name of class to instantiate
		     * @returns  {object} Instance of the model class
		     */
			getInstance: function(modelName) {
        		return new classMap[modelName]();
			}
		};
	}

}(angular));
