/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('YtelAPIV3Lib')
    .factory('ActivateStatusEnum', [ActivateStatusEnumModel]);

    function ActivateStatusEnumModel() {
        return {
            //TODO: Write general description for this element
            M_ACTIVATE: 1,
    
            //TODO: Write general description for this element
            DE_ACTIVATE: 0
        };
    }

}(angular));
