/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('YtelAPIV3Lib')
    .factory('Direction4Enum', [Direction4EnumModel]);

    function Direction4EnumModel() {
        return {
            //TODO: Write general description for this element
            MIN: 'in',
    
            //TODO: Write general description for this element
            OUT: 'out',
    
            //TODO: Write general description for this element
            BOTH: 'both'
        };
    }

}(angular));
