/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('YtelAPIV3Lib')
    .factory('Direction23Enum', [Direction23EnumModel]);

    function Direction23EnumModel() {
        return {
            //in direction
            MIN: 'in',
    
            //out direction
            OUT: 'out',
    
            //both
            BOTH: 'both'
        };
    }

}(angular));
