/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('YtelAPIV3Lib')
    .factory('GroupConfirmFile44Enum', [GroupConfirmFile44EnumModel]);

    function GroupConfirmFile44EnumModel() {
        return {
            //mp3 file
            MP_3: 'mp3',
    
            //wav file
            WAV: 'wav'
        };
    }

}(angular));
