/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('YtelAPIV3Lib')
    .factory('IfMachineEnum', [IfMachineEnumModel]);

    function IfMachineEnumModel() {
        return {
            //TODO: Write general description for this element
            MCONTINUE: 'continue',
    
            //TODO: Write general description for this element
            HANGUP: 'hangup'
        };
    }

}(angular));
