/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('YtelAPIV3Lib')
    .factory('MergeNumberEnum', [MergeNumberEnumModel]);

    function MergeNumberEnumModel() {
        return {
            //TODO: Write general description for this element
            ENUM_0: 0,
    
            //TODO: Write general description for this element
            ENUM_1: 1
        };
    }

}(angular));
