/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Message
 *
 * @constructor
 */
angular.module('YtelAPIV3Lib')
    .factory('Message', ['BaseModel', MessageModel]);

    function MessageModel(BaseModel) {
        var Message = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.apiVersion = this.getValue(obj.apiVersion);
            this.messageSid = this.getValue(obj.messageSid);
            this.from = this.getValue(obj.from);
            this.to = this.getValue(obj.to);
            this.messagePrice = this.getValue(obj.messagePrice);
            this.body = this.getValue(obj.body);
            this.dateSent = this.getValue(obj.dateSent);
            this.status = this.getValue(obj.status);
            this.templateId = this.getValue(obj.templateId);
            this.templateData = this.getValue(obj.templateData);
        };

        Message.prototype = new BaseModel();
        Message.prototype.constructor = Message;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Message.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'apiVersion', realName: 'ApiVersion' },
                { name: 'messageSid', realName: 'MessageSid' },
                { name: 'from', realName: 'From' },
                { name: 'to', realName: 'To' },
                { name: 'messagePrice', realName: 'MessagePrice' },
                { name: 'body', realName: 'Body' },
                { name: 'dateSent', realName: 'DateSent' },
                { name: 'status', realName: 'Status' },
                { name: 'templateId', realName: 'TemplateId' },
                { name: 'templateData', realName: 'TemplateData', type: 'TemplateData' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Message.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        Message.prototype.getApiVersion = function () {
            return this.apiVersion;
        };
    
        /**
         * Setter for ApiVersion
         * 
         * @param {string} value 
         */
        Message.prototype.setApiVersion = function (value) {
            this.apiVersion = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        Message.prototype.getMessageSid = function () {
            return this.messageSid;
        };
    
        /**
         * Setter for MessageSid
         * 
         * @param {string} value 
         */
        Message.prototype.setMessageSid = function (value) {
            this.messageSid = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        Message.prototype.getFrom = function () {
            return this.from;
        };
    
        /**
         * Setter for From
         * 
         * @param {string} value 
         */
        Message.prototype.setFrom = function (value) {
            this.from = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        Message.prototype.getTo = function () {
            return this.to;
        };
    
        /**
         * Setter for To
         * 
         * @param {string} value 
         */
        Message.prototype.setTo = function (value) {
            this.to = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        Message.prototype.getMessagePrice = function () {
            return this.messagePrice;
        };
    
        /**
         * Setter for MessagePrice
         * 
         * @param {string} value 
         */
        Message.prototype.setMessagePrice = function (value) {
            this.messagePrice = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        Message.prototype.getBody = function () {
            return this.body;
        };
    
        /**
         * Setter for Body
         * 
         * @param {string} value 
         */
        Message.prototype.setBody = function (value) {
            this.body = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        Message.prototype.getDateSent = function () {
            return this.dateSent;
        };
    
        /**
         * Setter for DateSent
         * 
         * @param {string} value 
         */
        Message.prototype.setDateSent = function (value) {
            this.dateSent = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        Message.prototype.getStatus = function () {
            return this.status;
        };
    
        /**
         * Setter for Status
         * 
         * @param {string} value 
         */
        Message.prototype.setStatus = function (value) {
            this.status = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        Message.prototype.getTemplateId = function () {
            return this.templateId;
        };
    
        /**
         * Setter for TemplateId
         * 
         * @param {string} value 
         */
        Message.prototype.setTemplateId = function (value) {
            this.templateId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {TemplateData}
         */
        Message.prototype.getTemplateData = function () {
            return this.templateData;
        };
    
        /**
         * Setter for TemplateData
         * 
         * @param {TemplateData} value 
         */
        Message.prototype.setTemplateData = function (value) {
            this.templateData = value;
        };
    
        return Message;
    }

}(angular));
