/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('YtelAPIV3Lib')
    .factory('NumbertypeEnum', [NumbertypeEnumModel]);

    function NumbertypeEnumModel() {
        return {
            //TODO: Write general description for this element
            ALL: 'all',
    
            //TODO: Write general description for this element
            VOICE: 'voice',
    
            //TODO: Write general description for this element
            SMS: 'sms'
        };
    }

}(angular));
