/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('YtelAPIV3Lib')
    .factory('StatusEnum', [StatusEnumModel]);

    function StatusEnumModel() {
        return {
            //TODO: Write general description for this element
            CANCELED: 'canceled',
    
            //TODO: Write general description for this element
            COMPLETED: 'completed'
        };
    }

}(angular));
