/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of TemplateData
 *
 * @constructor
 */
angular.module('YtelAPIV3Lib')
    .factory('TemplateData', ['BaseModel', TemplateDataModel]);

    function TemplateDataModel(BaseModel) {
        var TemplateData = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.companyname = this.getValue(obj.companyname);
            this.otpcode = this.getValue(obj.otpcode);
        };

        TemplateData.prototype = new BaseModel();
        TemplateData.prototype.constructor = TemplateData;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        TemplateData.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'companyname', realName: 'companyname' },
                { name: 'otpcode', realName: 'otpcode' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        TemplateData.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        TemplateData.prototype.getCompanyname = function () {
            return this.companyname;
        };
    
        /**
         * Setter for Companyname
         * 
         * @param {string} value 
         */
        TemplateData.prototype.setCompanyname = function (value) {
            this.companyname = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        TemplateData.prototype.getOtpcode = function () {
            return this.otpcode;
        };
    
        /**
         * Setter for Otpcode
         * 
         * @param {string} value 
         */
        TemplateData.prototype.setOtpcode = function (value) {
            this.otpcode = value;
        };
    
        return TemplateData;
    }

}(angular));
