/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('YtelAPIV3Lib')
    .factory('TypeEnum', [TypeEnumModel]);

    function TypeEnumModel() {
        return {
            //TODO: Write general description for this element
            TEXT: 'text',
    
            //TODO: Write general description for this element
            HTML: 'html'
        };
    }

}(angular));
