/**
  * YtelAPILib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('YtelAPILib')
    .factory('CallController', ['$q', 'Configuration', 'HttpClient', 'APIHelper', 'BaseController', CallController
    ]);

    function CallController($q, Configuration, HttpClient, APIHelper, BaseController) {
        return {
            /**
             * Retrieve a single voice call’s information by its CallSid.
             *
             * @param {string} callSid The unique identifier for the voice call.
             *
             * @return {promise<String>}
             */
            createCallsViewcalldetail: function (callSid) {

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/calls/viewcalldetail.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'callSid': callSid
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * Retrieve a single voice call’s information by its CallSid.
             *
             * @param {string} callsid The unique identifier for the voice call.
             *
             * @return {promise<String>}
             */
            createCallsViewcalls: function (callsid) {

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/calls/viewcalls.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'callsid': callsid
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * Play Dtmf and send the Digit
             *
             * @param {array}  input    Array with all options for search
             * @param {string} input['callSid'] The unique identifier of each call resource
             * @param {string} input['playDtmf'] DTMF digits to play to the call. 0-9, #, *, W, or w
             * @param {PlayDtmfDirectionEnum|null} input['playDtmfDirection'] [Optional] The leg of the call DTMF
             * digits should be sent to
             *
             * @return {promise<String>}
             */
            createCallsSenddigits: function (input) {
                // Assign default values
                input = input || {};

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/calls/senddigits.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'CallSid': input.callSid,
                    'PlayDtmf': input.playDtmf,
                    'PlayDtmfDirection': (input.playDtmfDirection !== null) ? input.playDtmfDirection : null
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * Initiate an outbound Ringless Voicemail through Ytel.
             *
             * @param {array}  input    Array with all options for search
             * @param {string} input['from'] A valid Ytel Voice enabled number (E.164 format) that will be
             * initiating the phone call.
             * @param {string} input['rVMCallerId'] A required secondary Caller ID for RVM to work.
             * @param {string} input['to'] A valid number (E.164 format) that will receive the phone call.
             * @param {string} input['voiceMailURL'] The URL requested once the RVM connects. A set of default
             * parameters will be sent here.
             * @param {string|null} input['method'] [Optional] Specifies the HTTP method used to request the
             * required URL once call connects.
             * @param {string|null} input['statusCallBackUrl'] [Optional] URL that can be requested to receive
             * notification when call has ended. A set of default
             * parameters will be sent here once the call is
             * finished.
             * @param {string|null} input['statsCallBackMethod'] [Optional] Specifies the HTTP method used to
             * request the required StatusCallBackUrl once call
             * connects.
             *
             * @return {promise<String>}
             */
            createCallsMakervm: function (input) {
                // Assign default values
                input = input || {};

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/calls/makervm.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'From': input.from,
                    'RVMCallerId': input.rVMCallerId,
                    'To': input.to,
                    'VoiceMailURL': input.voiceMailURL,
                    'Method': (input.method !== null) ? input.method : 'GET',
                    'StatusCallBackUrl': input.statusCallBackUrl,
                    'StatsCallBackMethod': input.statsCallBackMethod
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * A list of calls associated with your Ytel account
             *
             * @param {array}  input    Array with all options for search
             * @param {int|null} input['page'] [Optional] The page count to retrieve from the total results in the
             * collection. Page indexing starts at 1.
             * @param {int|null} input['pageSize'] [Optional] Number of individual resources listed in the response
             * per page
             * @param {string|null} input['to'] [Optional] Filter calls that were sent to this 10-digit number (E.
             * 164 format).
             * @param {string|null} input['from'] [Optional] Filter calls that were sent from this 10-digit number
             * (E.164 format).
             * @param {string|null} input['dateCreated'] [Optional] Return calls that are from a specified date.
             *
             * @return {promise<String>}
             */
            createCallsListcalls: function (input) {
                // Assign default values
                input = input || {};

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/calls/listcalls.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'Page': (input.page !== null) ? input.page : 1,
                    'PageSize': (input.pageSize !== null) ? input.pageSize : 10,
                    'To': input.to,
                    'From': input.from,
                    'DateCreated': input.dateCreated
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * Interrupt the Call by Call Sid
             *
             * @param {array}  input    Array with all options for search
             * @param {string} input['callSid'] The unique identifier for voice call that is in progress.
             * @param {string|null} input['url'] [Optional] URL the in-progress call will be redirected to
             * @param {string|null} input['method'] [Optional] The method used to request the above Url parameter
             * @param {Status24Enum|null} input['status'] [Optional] Status to set the in-progress call to
             *
             * @return {promise<String>}
             */
            createCallsInterruptcalls: function (input) {
                // Assign default values
                input = input || {};

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/calls/interruptcalls.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'CallSid': input.callSid,
                    'Url': input.url,
                    'Method': input.method,
                    'Status': (input.status !== null) ? input.status : null
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * Start or stop recording of an in-progress voice call.
             *
             * @param {array}  input    Array with all options for search
             * @param {string} input['callSid'] The unique identifier of each call resource
             * @param {bool} input['record'] Set true to initiate recording or false to terminate recording
             * @param {DirectionEnum|null} input['direction'] [Optional] The leg of the call to record
             * @param {int|null} input['timeLimit'] [Optional] Time in seconds the recording duration should not
             * exceed
             * @param {string|null} input['callBackUrl'] [Optional] URL consulted after the recording completes
             * @param {FileformatEnum|null} input['fileformat'] [Optional] Format of the recording file. Can be .
             * mp3 or .wav
             *
             * @return {promise<String>}
             */
            createCallsRecordcalls: function (input) {
                // Assign default values
                input = input || {};

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/calls/recordcalls.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'CallSid': input.callSid,
                    'Record': input.record,
                    'Direction': (input.direction !== null) ? input.direction : null,
                    'TimeLimit': input.timeLimit,
                    'CallBackUrl': input.callBackUrl,
                    'Fileformat': (input.fileformat !== null) ? input.fileformat : null
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * Play Audio from a url
             *
             * @param {array}  input    Array with all options for search
             * @param {string} input['callSid'] The unique identifier of each call resource
             * @param {string} input['audioUrl'] URL to sound that should be played. You also can add more than one
             * audio file using semicolons e.g. http://example.com/audio1.mp3;
             * http://example.com/audio2.wav
             * @param {string} input['sayText'] Valid alphanumeric string that should be played to the In-progress
             * call.
             * @param {int|null} input['length'] [Optional] Time limit in seconds for audio play back
             * @param {DirectionEnum|null} input['direction'] [Optional] The leg of the call audio will be played
             * to
             * @param {bool|null} input['mix'] [Optional] If false, all other audio will be muted
             *
             * @return {promise<String>}
             */
            createCallsPlayaudios: function (input) {
                // Assign default values
                input = input || {};

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/calls/playaudios.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'CallSid': input.callSid,
                    'AudioUrl': input.audioUrl,
                    'SayText': input.sayText,
                    'Length': input.length,
                    'Direction': (input.direction !== null) ? input.direction : null,
                    'Mix': input.mix
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * Add audio voice effects to the an in-progress voice call.
             *
             * @param {array}  input    Array with all options for search
             * @param {string} input['callSid'] The unique identifier for the in-progress voice call.
             * @param {AudioDirectionEnum|null} input['audioDirection'] [Optional] The direction the audio effect
             * should be placed on. If IN, the effects
             * will occur on the incoming audio stream. If
             * OUT, the effects will occur on the outgoing
             * audio stream.
             * @param {double|null} input['pitchSemiTones'] [Optional] Set the pitch in semitone (half-step)
             * intervals. Value between -14 and 14
             * @param {double|null} input['pitchOctaves'] [Optional] Set the pitch in octave intervals.. Value
             * between -1 and 1
             * @param {double|null} input['pitch'] [Optional] Set the pitch (lowness/highness) of the audio. The
             * higher the value, the higher the pitch. Value greater than 0
             * @param {double|null} input['rate'] [Optional] Set the rate for audio. The lower the value, the lower
             * the rate. value greater than 0
             * @param {double|null} input['tempo'] [Optional] Set the tempo (speed) of the audio. A higher value
             * denotes a faster tempo. Value greater than 0
             *
             * @return {promise<String>}
             */
            createCallsVoiceeffect: function (input) {
                // Assign default values
                input = input || {};

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/calls/voiceeffect.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'CallSid': input.callSid,
                    'AudioDirection': (input.audioDirection !== null) ? input.audioDirection : null,
                    'PitchSemiTones': input.pitchSemiTones,
                    'PitchOctaves': input.pitchOctaves,
                    'Pitch': input.pitch,
                    'Rate': input.rate,
                    'Tempo': input.tempo
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * Group Call
             *
             * @param {array}  input    Array with all options for search
             * @param {string} input['from'] This number to display on Caller ID as calling
             * @param {string} input['to'] Please enter multiple E164 number. You can add max 10 numbers. Add
             * numbers separated with comma. e.g : 1111111111,2222222222
             * @param {string} input['url'] URL requested once the call connects
             * @param {string} input['groupConfirmKey'] Define the DTMF that the called party should send to bridge
             * the call. Allowed Values : 0-9, #, *
             * @param {GroupConfirmFileEnum} input['groupConfirmFile'] Specify the audio file you want to play when
             * the called party picks up the call
             * @param {string|null} input['method'] [Optional] Specifies the HTTP method used to request the
             * required URL once call connects.
             * @param {string|null} input['statusCallBackUrl'] [Optional] URL that can be requested to receive
             * notification when call has ended. A set of default
             * parameters will be sent here once the call is
             * finished.
             * @param {string|null} input['statusCallBackMethod'] [Optional] Specifies the HTTP methodlinkclass
             * used to request StatusCallbackUrl.
             * @param {string|null} input['fallBackUrl'] [Optional] URL requested if the initial Url parameter
             * fails or encounters an error
             * @param {string|null} input['fallBackMethod'] [Optional] Specifies the HTTP method used to request
             * the required FallbackUrl once call connects.
             * @param {string|null} input['heartBeatUrl'] [Optional] URL that can be requested every 60 seconds
             * during the call to notify of elapsed time and pass other
             * general information.
             * @param {string|null} input['heartBeatMethod'] [Optional] Specifies the HTTP method used to request
             * HeartbeatUrl.
             * @param {int|null} input['timeout'] [Optional] Time (in seconds) we should wait while the call is
             * ringing before canceling the call
             * @param {string|null} input['playDtmf'] [Optional] DTMF Digits to play to the call once it connects.
             * 0-9, #, or *
             * @param {string|null} input['hideCallerId'] [Optional] Specifies if the caller id will be hidden
             * @param {bool|null} input['record'] [Optional] Specifies if the call should be recorded
             * @param {string|null} input['recordCallBackUrl'] [Optional] Recording parameters will be sent here
             * upon completion
             * @param {string|null} input['recordCallBackMethod'] [Optional] Method used to request the
             * RecordCallback URL.
             * @param {bool|null} input['transcribe'] [Optional] Specifies if the call recording should be
             * transcribed
             * @param {string|null} input['transcribeCallBackUrl'] [Optional] Transcription parameters will be sent
             * here upon completion
             *
             * @return {promise<String>}
             */
            createCallsGroupcall: function (input) {
                // Assign default values
                input = input || {};

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/calls/groupcall.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'From': input.from,
                    'To': input.to,
                    'Url': input.url,
                    'GroupConfirmKey': input.groupConfirmKey,
                    'GroupConfirmFile': (input.groupConfirmFile !== null) ? input.groupConfirmFile : null,
                    'Method': input.method,
                    'StatusCallBackUrl': input.statusCallBackUrl,
                    'StatusCallBackMethod': input.statusCallBackMethod,
                    'FallBackUrl': input.fallBackUrl,
                    'FallBackMethod': input.fallBackMethod,
                    'HeartBeatUrl': input.heartBeatUrl,
                    'HeartBeatMethod': input.heartBeatMethod,
                    'Timeout': input.timeout,
                    'PlayDtmf': input.playDtmf,
                    'HideCallerId': input.hideCallerId,
                    'Record': input.record,
                    'RecordCallBackUrl': input.recordCallBackUrl,
                    'RecordCallBackMethod': input.recordCallBackMethod,
                    'Transcribe': input.transcribe,
                    'TranscribeCallBackUrl': input.transcribeCallBackUrl
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * You can experiment with initiating a call through Ytel and view the request response generated when
             * doing so and get the response in json
             *
             * @param {array}  input    Array with all options for search
             * @param {string} input['from'] A valid Ytel Voice enabled number (E.164 format) that will be
             * initiating the phone call.
             * @param {string} input['to'] To number
             * @param {string} input['url'] URL requested once the call connects
             * @param {string|null} input['method'] [Optional] Specifies the HTTP method used to request the
             * required URL once call connects.
             * @param {string|null} input['statusCallBackUrl'] [Optional] URL that can be requested to receive
             * notification when call has ended. A set of default
             * parameters will be sent here once the call is
             * finished.
             * @param {string|null} input['statusCallBackMethod'] [Optional] Specifies the HTTP methodlinkclass
             * used to request StatusCallbackUrl.
             * @param {string|null} input['fallBackUrl'] [Optional] URL requested if the initial Url parameter
             * fails or encounters an error
             * @param {string|null} input['fallBackMethod'] [Optional] Specifies the HTTP method used to request
             * the required FallbackUrl once call connects.
             * @param {string|null} input['heartBeatUrl'] [Optional] URL that can be requested every 60 seconds
             * during the call to notify of elapsed tim
             * @param {string|null} input['heartBeatMethod'] [Optional] Specifies the HTTP method used to request
             * HeartbeatUrl.
             * @param {int|null} input['timeout'] [Optional] Time (in seconds) Ytel should wait while the call is
             * ringing before canceling the call
             * @param {string|null} input['playDtmf'] [Optional] DTMF Digits to play to the call once it connects.
             * 0-9, #, or *
             * @param {bool|null} input['hideCallerId'] [Optional] Specifies if the caller id will be hidden
             * @param {bool|null} input['record'] [Optional] Specifies if the call should be recorded
             * @param {string|null} input['recordCallBackUrl'] [Optional] Recording parameters will be sent here
             * upon completion
             * @param {string|null} input['recordCallBackMethod'] [Optional] Method used to request the
             * RecordCallback URL.
             * @param {bool|null} input['transcribe'] [Optional] Specifies if the call recording should be
             * transcribed
             * @param {string|null} input['transcribeCallBackUrl'] [Optional] Transcription parameters will be sent
             * here upon completion
             * @param {IfMachineEnum|null} input['ifMachine'] [Optional] How Ytel should handle the receiving
             * numbers voicemail machine
             * @param {string|null} input['ifMachineUrl'] [Optional] URL requested when IfMachine=continue
             * @param {string|null} input['ifMachineMethod'] [Optional] Method used to request the IfMachineUrl.
             * @param {bool|null} input['feedback'] [Optional] Specify if survey should be enable or not
             * @param {string|null} input['surveyId'] [Optional] The unique identifier for the survey.
             *
             * @return {promise<String>}
             */
            createCallsMakecall: function (input) {
                // Assign default values
                input = input || {};

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/calls/makecall.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'From': input.from,
                    'To': input.to,
                    'Url': input.url,
                    'Method': input.method,
                    'StatusCallBackUrl': input.statusCallBackUrl,
                    'StatusCallBackMethod': input.statusCallBackMethod,
                    'FallBackUrl': input.fallBackUrl,
                    'FallBackMethod': input.fallBackMethod,
                    'HeartBeatUrl': input.heartBeatUrl,
                    'HeartBeatMethod': input.heartBeatMethod,
                    'Timeout': input.timeout,
                    'PlayDtmf': input.playDtmf,
                    'HideCallerId': input.hideCallerId,
                    'Record': input.record,
                    'RecordCallBackUrl': input.recordCallBackUrl,
                    'RecordCallBackMethod': input.recordCallBackMethod,
                    'Transcribe': input.transcribe,
                    'TranscribeCallBackUrl': input.transcribeCallBackUrl,
                    'IfMachine': (input.ifMachine !== null) ? input.ifMachine : null,
                    'IfMachineUrl': input.ifMachineUrl,
                    'IfMachineMethod': input.ifMachineMethod,
                    'Feedback': input.feedback,
                    'SurveyId': input.surveyId
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            }
        };
    }

}(angular));
