/**
  * YtelAPILib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('YtelAPILib')
    .factory('ShortCodeController', ['$q',
        'Configuration',
        'HttpClient',
        'APIHelper',
        'BaseController',
        ShortCodeController
    ]);

    function ShortCodeController($q, Configuration, HttpClient, APIHelper, BaseController) {
        return {
            /**
             * Retrieve a list of Short Code assignment associated with your Ytel account.
             *
             * @param {array}  input    Array with all options for search
             * @param {string|null} input['shortcode'] [Optional] Only list Short Code Assignment sent from this
             * Short Code
             * @param {string|null} input['page'] [Optional] The page count to retrieve from the total results in
             * the collection. Page indexing starts at 1.
             * @param {string|null} input['pagesize'] [Optional] The count of objects to return per page.
             *
             * @return {promise<String>}
             */
            createDedicatedshortcodeListshortcode: function (input) {
                // Assign default values
                input = input || {};

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/dedicatedshortcode/listshortcode.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'Shortcode': input.shortcode,
                    'page': input.page,
                    'pagesize': input.pagesize
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * Update a dedicated shortcode.
             *
             * @param {array}  input    Array with all options for search
             * @param {string} input['shortcode'] List of valid dedicated shortcode to your Ytel account.
             * @param {string|null} input['friendlyName'] [Optional] User generated name of the dedicated shortcode.
             * @param {string|null} input['callbackMethod'] [Optional] Specifies the HTTP method used to request
             * the required StatusCallBackUrl once call connects.
             * @param {string|null} input['callbackUrl'] [Optional] URL that can be requested to receive
             * notification when call has ended. A set of default
             * parameters will be sent here once the call is finished.
             * @param {string|null} input['fallbackMethod'] [Optional] Specifies the HTTP method used to request
             * the required FallbackUrl once call connects.
             * @param {string|null} input['fallbackUrl'] [Optional] URL used if any errors occur during execution
             * of InboundXML or at initial request of the required Url
             * provided with the POST.
             *
             * @return {promise<String>}
             */
            createDedicatedshortcodeUpdateshortcode: function (input) {
                // Assign default values
                input = input || {};

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/dedicatedshortcode/updateshortcode.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'Shortcode': input.shortcode,
                    'FriendlyName': input.friendlyName,
                    'CallbackMethod': input.callbackMethod,
                    'CallbackUrl': input.callbackUrl,
                    'FallbackMethod': input.fallbackMethod,
                    'FallbackUrl': input.fallbackUrl
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * Retrieve a single Short Code object by its shortcode assignment.
             *
             * @param {string} shortcode List of valid Dedicated Short Code to your Ytel account
             *
             * @return {promise<String>}
             */
            createDedicatedshortcodeViewshortcode: function (shortcode) {

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/dedicatedshortcode/viewshortcode.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'Shortcode': shortcode
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * View a single Sms Short Code message.
             *
             * @param {string} messageSid The unique identifier for the sms resource
             *
             * @return {promise<String>}
             */
            createShortcodeViewsms: function (messageSid) {

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/shortcode/viewsms.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'MessageSid': messageSid
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * Retrive a list of inbound Sms Short Code messages associated with your Ytel account.
             *
             * @param {array}  input    Array with all options for search
             * @param {int|null} input['page'] [Optional] The page count to retrieve from the total results in the
             * collection. Page indexing starts at 1.
             * @param {int|null} input['pagesize'] [Optional] Number of individual resources listed in the response
             * per page
             * @param {string|null} input['from'] [Optional] Only list SMS messages sent from this number
             * @param {string|null} input['shortcode'] [Optional] Only list SMS messages sent to Shortcode
             * @param {string|null} input['datecreated'] [Optional] Only list SMS messages sent in the specified
             * date MAKE REQUEST
             *
             * @return {promise<String>}
             */
            createDedicatedshortcodeGetinboundsms: function (input) {
                // Assign default values
                input = input || {};

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/dedicatedshortcode/getinboundsms.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'page': (input.page !== null) ? input.page : 1,
                    'pagesize': (input.pagesize !== null) ? input.pagesize : 10,
                    'From': input.from,
                    'Shortcode': input.shortcode,
                    'Datecreated': input.datecreated
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * Send Dedicated Shortcode
             *
             * @param {array}  input    Array with all options for search
             * @param {int} input['shortcode'] Your dedicated shortcode
             * @param {double} input['to'] The number to send your SMS to
             * @param {string} input['body'] The body of your message
             * @param {string|null} input['method'] [Optional] Specifies the HTTP method used to request the
             * required URL once the Short Code message is sent.GET or POST
             * @param {string|null} input['messagestatuscallback'] [Optional] URL that can be requested to receive
             * notification when Short Code message was sent.
             *
             * @return {promise<String>}
             */
            createDedicatedshortcodeSendsms: function (input) {
                // Assign default values
                input = input || {};

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/dedicatedshortcode/sendsms.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'shortcode': input.shortcode,
                    'to': input.to,
                    'body': input.body,
                    'method': input.method,
                    'messagestatuscallback': input.messagestatuscallback
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * Retrieve a list of Short Code messages.
             *
             * @param {array}  input    Array with all options for search
             * @param {string|null} input['shortcode'] [Optional] Only list messages sent from this Short Code
             * @param {string|null} input['to'] [Optional] Only list messages sent to this number
             * @param {string|null} input['dateSent'] [Optional] Only list messages sent with the specified date
             * @param {int|null} input['page'] [Optional] The page count to retrieve from the total results in the
             * collection. Page indexing starts at 1.
             * @param {int|null} input['pageSize'] [Optional] The count of objects to return per page.
             *
             * @return {promise<String>}
             */
            createShortcodeListsms: function (input) {
                // Assign default values
                input = input || {};

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/shortcode/listsms.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'Shortcode': input.shortcode,
                    'To': input.to,
                    'DateSent': input.dateSent,
                    'Page': (input.page !== null) ? input.page : 1,
                    'PageSize': (input.pageSize !== null) ? input.pageSize : 10
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            }
        };
    }

}(angular));
