/**
  * YtelAPILib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('YtelAPILib')
    .factory('SubAccountController', ['$q',
        'Configuration',
        'HttpClient',
        'APIHelper',
        'BaseController',
        SubAccountController
    ]);

    function SubAccountController($q, Configuration, HttpClient, APIHelper, BaseController) {
        return {
            /**
             * Suspend or unsuspend
             *
             * @param {array}  input    Array with all options for search
             * @param {string} input['subAccountSID'] The SubaccountSid to be activated or suspended
             * @param {MActivateEnum} input['mActivate'] 0 to suspend or 1 to activate
             *
             * @return {promise<String>}
             */
            createUserSubaccountactivation: function (input) {
                // Assign default values
                input = input || {};

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/user/subaccountactivation.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'SubAccountSID': input.subAccountSID,
                    'mActivate': (input.mActivate !== null) ? input.mActivate : null
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * Delete sub account or merge numbers into parent
             *
             * @param {array}  input    Array with all options for search
             * @param {string} input['subAccountSID'] The SubaccountSid to be deleted
             * @param {MergeNumberEnum} input['mergeNumber'] 0 to delete or 1 to merge numbers to parent account.
             *
             * @return {promise<String>}
             */
            createUserDeletesubaccount: function (input) {
                // Assign default values
                input = input || {};

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/user/deletesubaccount.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'SubAccountSID': input.subAccountSID,
                    'MergeNumber': (input.mergeNumber !== null) ? input.mergeNumber : null
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            },
            /**
             * Create a sub user account under the parent account
             *
             * @param {array}  input    Array with all options for search
             * @param {string} input['firstName'] Sub account user first name
             * @param {string} input['lastName'] sub account user last name
             * @param {string} input['email'] Sub account email address
             * @param {string} input['friendlyName'] Descriptive name of the sub account
             * @param {string} input['password'] The password of the sub account.  Please make sure to make as
             * password that is at least 8 characters long, contain a symbol,
             * uppercase and a number.
             *
             * @return {promise<String>}
             */
            createUserCreatesubaccount: function (input) {
                // Assign default values
                input = input || {};

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/user/createsubaccount.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'FirstName': input.firstName,
                    'LastName': input.lastName,
                    'Email': input.email,
                    'FriendlyName': input.friendlyName,
                    'Password': input.password
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            }
        };
    }

}(angular));
