/**
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('YtelAPIV3Lib')
    .factory('UsageController', ['$q', 'Configuration', 'HttpClient', 'APIHelper', 'BaseController', UsageController
    ]);

    function UsageController($q, Configuration, HttpClient, APIHelper, BaseController) {
        return {
            /**
             * Retrieve usage metrics regarding your Ytel account. The results includes inbound/outbound voice calls
             * and inbound/outbound SMS messages as well as carrier lookup requests.
             *
             * @param {ProductCodeEnum|null} productCode [Optional] Filter usage results by product type.
             * @param {string|null} startDate [Optional] Filter usage objects by start date.
             * @param {string|null} endDate [Optional] Filter usage objects by end date.
             * @param {string|null} includeSubAccounts [Optional] Will include all subaccount usage data
             *
             * @return {promise<String>}
             */
            createListUsage: function (productCode, startDate, endDate, includeSubAccounts) {

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/usage/listusage.json';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'ProductCode': (productCode !== null) ? productCode : null,
                    'startDate': startDate,
                    'endDate': endDate,
                    'IncludeSubAccounts': includeSubAccounts
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    username: Configuration.basicAuthUserName,
                    password: Configuration.basicAuthPassword,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            }
        };
    }

}(angular));
